services:
  # Ergs scheduler daemon - fetches data from datasources
  ergs-serve:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ergs-serve
    command: ["ergs", "serve", "--config", "/config/config.toml"]
    volumes:
      - ergs-data:/data
      - ./config.toml:/config/config.toml:ro,z
    environment:
      - TZ=UTC
    restart: unless-stopped
    healthcheck:
      disable: true

  # Ergs web interface - serves the web UI and API
  ergs-web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ergs-web
    command:
      ["ergs", "web", "--host", "0.0.0.0", "--config", "/config/config.toml"]
    ports:
      - "7117:8080"
    volumes:
      - ergs-data:/data
      - ./config.toml:/config/config.toml:ro,z
    environment:
      - TZ=UTC
    restart: unless-stopped
    depends_on:
      - ergs-serve
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/",
        ]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3

volumes:
  ergs-data:
    driver: local
