# Ergs Configuration File for Docker
# Copy this to config.toml and edit with your settings

# Storage directory - must be /data for Docker
storage_dir = '/data'
event_socket_path = '/data/.ergs.sock'

[importer]
api_key = "this-should-be-a-secret-but-its-not"

# Example: Hacker News datasource
[datasources.hackernews]
type = 'hackernews'
interval = '1h0m0s'
[datasources.hackernews.config]
fetch_top = true
fetch_new = false
max_items = 100
fetch_comments = false

# Example: RSS feeds
[datasources.rss]
type = 'rss'
interval = '2h0m0s'
[datasources.rss.config]
urls = [
    'https://feeds.arstechnica.com/arstechnica/index',
    'https://www.phoronix.com/rss.php'
]
max_items = 50

[datasources.importer]
type = "importer"
[datasources.importer.config]
api_url = "http://ergs-importer:7119"
api_key = "this-should-be-a-secret-but-its-not"

# Additional datasources can be configured here
# See pkg/config/config.toml.sample for all available options
