// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/rubiojr/ergs/cmd/web/components/types"

func Layout(data types.PageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(data.Title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `cmd/web/components/layout.templ`, Line: 11, Col: 22}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</title><link rel=\"icon\" type=\"image/x-icon\" href=\"/static/favicon.ico\"><link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"/static/favicon-32x32.png\"><link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"/static/favicon-16x16.png\"><link rel=\"stylesheet\" href=\"/static/style.css\"><link rel=\"stylesheet\" href=\"/static/choices.min.css\"></head><body class=\"theme-polar-night\"><header><div class=\"container\"><div class=\"header-content\"><h1><a href=\"/\" style=\"text-decoration: none; color: inherit\" class=\"brand\"><span class=\"logo\" style=\"display:inline-block;vertical-align:middle;margin-right:8px;\"><svg width=\"36\" height=\"24\" viewBox=\"0 0 72 48\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Ergs Dune Logo\"><defs><linearGradient id=\"duneGrad\" x1=\"0%\" y1=\"0%\" x2=\"0%\" y2=\"100%\"><stop offset=\"0%\" stop-color=\"#ebcb8b\"></stop> <stop offset=\"55%\" stop-color=\"#d08770\"></stop> <stop offset=\"100%\" stop-color=\"#bf616a\"></stop></linearGradient></defs> <path d=\"M4 34c6-2 12-6 18-10 9-6 14-6 22 0 3 2 6 4 10 5 4 2 8 2 14 1v10H4V34Z\" fill=\"url(#duneGrad)\"></path> <path d=\"M4 34c6-2 12-6 18-10 9-6 14-6 22 0 3 2 6 4 10 5 4 2 8 2 14 1\" fill=\"none\" stroke=\"rgba(255,255,255,0.20)\" stroke-width=\"2\" stroke-linecap=\"round\"></path> <circle cx=\"52\" cy=\"14\" r=\"5\" fill=\"#ebcb8b\" opacity=\"0.9\"></circle></svg></span> <span style=\"vertical-align:middle;display:inline-block;\">Ergs Data Explorer</span></a></h1><nav><a href=\"/\">Home</a> <a href=\"/search\">Search</a> <a href=\"/firehose\">Firehose</a> <a href=\"/datasources\">Datasources</a></nav><div class=\"theme-toggle\" id=\"theme-toggle\"><div class=\"theme-dot polar-night\" data-theme=\"polar-night\" title=\"Polar Night\"></div><div class=\"theme-dot frost\" data-theme=\"frost\" title=\"Frost\"></div></div></div></div></header><main><div class=\"container\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if data.Error != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"alert alert-error\"><strong>Error:</strong> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(data.Error)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `cmd/web/components/layout.templ`, Line: 58, Col: 43}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if data.Success != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div class=\"alert alert-success\"><strong>Success:</strong> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(data.Success)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `cmd/web/components/layout.templ`, Line: 63, Col: 47}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div></main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if data.Version != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<footer><div class=\"container\"><div class=\"footer-content\" style=\"padding: 0.75rem 0; font-size: 0.75rem; color: #6c757d; text-align: center;\"><span>Ergs v")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(data.Version)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `cmd/web/components/layout.templ`, Line: 73, Col: 33}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</span></div></div></footer>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<script>\n\t\t\t\t// Theme + active navigation handling\n\t\t\t\tdocument.addEventListener(\"DOMContentLoaded\", function () {\n\t\t\t\t\t// Active nav highlighting\n\t\t\t\t\tconst currentPath = window.location.pathname;\n\t\t\t\t\tdocument.querySelectorAll(\"nav a\").forEach((link) => {\n\t\t\t\t\t\tif (\n\t\t\t\t\t\t\tlink.getAttribute(\"href\") === currentPath ||\n\t\t\t\t\t\t\t(currentPath.startsWith(\"/datasource/\") &&\n\t\t\t\t\t\t\t\tlink.getAttribute(\"href\") === \"/datasources\") ||\n\t\t\t\t\t\t\t(currentPath.startsWith(\"/firehose\") &&\n\t\t\t\t\t\t\t\tlink.getAttribute(\"href\") === \"/firehose\")\n\t\t\t\t\t\t) {\n\t\t\t\t\t\t\tlink.classList.add(\"active\");\n\t\t\t\t\t\t}\n\t\t\t\t\t});\n\n\t\t\t\t\t// Theme handling\n\t\t\t\t\tconst defaultTheme = \"polar-night\"; // default dark theme (matches initial body class)\n\t\t\t\t\tconst stored = localStorage.getItem(\"ergs-theme\") || defaultTheme;\n\t\t\t\t\tapplyTheme(stored);\n\n\t\t\t\t\tfunction applyTheme(name) {\n\t\t\t\t\t\tdocument.body.classList.remove(\"theme-polar-night\", \"theme-frost\");\n\t\t\t\t\t\tdocument.body.classList.add(\"theme-\" + name);\n\t\t\t\t\t\tlocalStorage.setItem(\"ergs-theme\", name);\n\t\t\t\t\t\tdocument\n\t\t\t\t\t\t\t.querySelectorAll(\".theme-dot\")\n\t\t\t\t\t\t\t.forEach((d) => d.classList.remove(\"active\"));\n\t\t\t\t\t\tconst activeDot = document.querySelector(\n\t\t\t\t\t\t\t'.theme-dot[data-theme=\"' + name + '\"]'\n\t\t\t\t\t\t);\n\t\t\t\t\t\tif (activeDot) activeDot.classList.add(\"active\");\n\t\t\t\t\t}\n\n\t\t\t\t\tdocument.querySelectorAll(\".theme-dot\").forEach((dot) => {\n\t\t\t\t\t\tdot.addEventListener(\"click\", () =>\n\t\t\t\t\t\t\tapplyTheme(dot.getAttribute(\"data-theme\"))\n\t\t\t\t\t\t);\n\t\t\t\t\t});\n\t\t\t\t});\n\t\t\t</script><script src=\"/static/choices.min.js\"></script><script src=\"/static/script.js\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
